/*
 * This file is part of the Silky Client distribution.
 * Copyright (c) 2026 pivosos2007.
 *
 * Licensed under the GNU General Public License v3.0.
 */

package silky.client.runtime;

import net.fabricmc.loader.api.FabricLoader;

/** Build metadata resolved from the Fabric metadata generated by Gradle. */
public final class SilkyBuild {
    private static final String MOD_ID = "silky";
    private static final String FALLBACK_VERSION = "dev";
    private static volatile String cachedVersion;

    private SilkyBuild() {
    }

    public static String version() {
        String cached = cachedVersion;
        if (cached != null) return cached;

        String resolved = FabricLoader.getInstance()
                .getModContainer(MOD_ID)
                .map(container -> container.getMetadata().getVersion().getFriendlyString())
                .filter(value -> value != null && !value.isBlank())
                .orElse(FALLBACK_VERSION);
        cachedVersion = resolved;
        return resolved;
    }
}
