# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21
yarn_mappings=1.21+build.7
loader_version=0.16.14
# Mod Properties
mod_id=silky
mod_name=Silky Client
mod_version=0.1.4
mod_license=GPL-3.0-only
maven_group=pivosos2007
archives_base_name=silky
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.100.4+1.21
sodium_version=mc1.21-0.6.0-beta.1-fabric
iris_version=1.8.0-beta.1+1.21-fabric
immediatelyfast_version=1.2.21+1.21.1-fabric
xaero_minimap_version=24.7.1_Fabric_1.21
xaero_worldmap_version=1.39.0_Fabric_1.21
viafabricplus_version=3.4.20
entityculling_version=1.6.5
